### ISSUE TITLE
Question about hosting.

### ISSUE THREAD

**Issue by GollyJer** [tomimick/restpie3#2]
Hi! I'm pretty new to python backend work and what you've put together here fits very well with the tooling I've leaned towards in my research.

What is unclear, to me, is the simplest way to host something like this. I'm looking for the simplest approach to establish an MVP product and was hoping to get up and running with something likehttps://www.pythonanywhere.com but I'm not sure if that's appropriate for the tool-chain you've put together.

What do you recommend for a quick and dirty but usable deploy?

Thanks so much for your effort with restpie3. I know it's not "free" for people to do work like this.

Best,
Jeremy

**Comment by tomimick** [comment]
For hosting I prefer a simple vanilla Linux VPS servers as they are cheap, starting $5/month, and provide enough resources and the best freedom to experiment and install any software. Granted, you need to know the basic of working with Linux and command line. For RESTPie3, you need to install PostgreSQL and Redis in addition to the python app itself. I wrote some instructions in the readme and the net is full of guides too.

If the idea of Linux setup frightens you, then maybe better look for more packaged solutions. I don't know about Pythonanywhere so can't comment. Heroku was/is very popular too.

(Sorry about delay - I'm not getting notifications.)
