### ISSUE TITLE
Listening to multiple ports

### ISSUE THREAD

**Issue by invictusro** [tomimick/restpie3#4]
Hello, as I can saw the script is only made to listen to one port. How I can change that port because I have multiples raspberries connected to the same network and I was wondering if I can use port forward to do this. Thank you!

Also, it's possible to connect to call the API remote with the external IP and a port to know which raspberry it is

**Comment by tomimick** [comment]
The HTTP port is configured in uwsgi.ini:
http = 0.0.0.0:80

You can listen on multiple ports by adding more of these lines.

Not sure what exactly is your second question...

**Comment by tomimick** [comment]
Question answered, I think, so closing this.
